astraBaby/astraBaby/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('astraKroha.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

astraBaby/astraKroha/urls.py
from django.urls import path, re_path

from django.views.generic import TemplateView

from .views import (
    index,
    product_view,
    category_view,
    cart_view,
    add_to_cart_view,
    remove_from_cart_view,
    update_qty,
    checkout_view,
    order_create_view,
    make_order_view,
    about_view, contact_view, pay_view, delivery_view)


urlpatterns = [
    re_path(r'category/(?P<category_slug>[-\w]+)/$', category_view, name='category_view_url'),
    re_path(r'product/(?P<product_slug>[-\w]+)/$', product_view, name='product_view_url'),
    path('add_to_cart/$', add_to_cart_view, name='add_to_cart_view_url'),#(?P<product_slug>[-\w]+)/
    path('remove_from_cart_view/$', remove_from_cart_view, name='remove_from_cart_url'),#re_path(r'remove_from_cart_view/(?P<product_slug>[-\w]+)/$', remove_from_cart_view, name='remove_from_cart_url'),
    path('update_qty/', update_qty, name='update_qty_url'),
    path('cart/', cart_view, name='cart_view_url'),
    path('checkout/', checkout_view, name='checkout_view_url'),
    path('order/', order_create_view, name='order_create_view_url'),
	path('make_order/', make_order_view, name='make_order_url'),
    path('thank_you/', TemplateView.as_view(template_name='astraKroha/thank_you.html'), name='thank_you'),
	path('about/', about_view, name='about_url'),
	path('contact/', contact_view, name='contact_url'),
	path('pay/', pay_view, name='pay_url'),
	path('delivery/', delivery_view, name='delivery_url'),
    path('', index, name='index_url'),
]

astraBaby/astraKroha/models.py
from __future__ import unicode_literals
from django.db import models

from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save
from pytz import unicode
from django.utils.text import slugify
from transliterate import translit
from decimal import Decimal
from django.conf import settings



def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)



class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)
    image = models.ImageField(upload_to=image_folder, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_view_url', kwargs={'category_slug': self.slug})



def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name),'ru', reversed=True))
        instance.slug = slug


pre_save.connect(pre_save_category_slug, sender=Category)


class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name





class ProductManager(models.Manager):
    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    available = models.BooleanField(default=True)
    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_view_url', kwargs={'product_slug': self.slug})

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.title)


class Cart(models.Model):
    item = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)


    def __str__(self):
        return str(self.id)


    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.item.all():
            cart.item.add(new_item)
            cart.save()


    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.item.all():
            if cart_item.product == product:
                cart.item.remove(cart_item)
                cart.save()


    def change_qty(self, qty, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.qty = int(qty)
        cart_item.item_total = int(qty) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.item.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()



ORDER_STATUS_CHOICES = (
    ('Принят в обработку','Принят в обработку'),
    ('Выполняется','Выполняется'),
    ('Оплачен','Оплачен')
)

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(Cart)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying = models.CharField(
        max_length=40,
        choices=(('Самовывоз','Самовывоз'), ('Доставка', 'Доставка')),
        default='Самовывоз'
    )
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES)

    def __str__(self):
        return "Заказа №{0}".format(str(self.id))

astraBaby/astraKroha/forms.py
from django import forms
from django.utils import timezone



class OrderForm(forms.Form):
    name = forms.CharField()
    last_name = forms.CharField(required=False)
    phone = forms.CharField()
    buying_type = forms.ChoiceField(widget=forms.Select(), choices=([("self", "Самовывоз"), ("delivery", "Доставка")]))
    date = forms.DateField(widget=forms.SelectDateWidget(), initial=timezone.now())
    address = forms.CharField(required=False)
    comments = forms.CharField(widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args,**kwargs)
        self.fields['name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['phone'].label = 'Контактный телефон'
        self.fields['phone'].help_text = 'Внимательно заполняйте номер телефона - это важно!'
        self.fields['buying_type'].label = 'Способ получения'
        self.fields['address'].label = 'Адрес доставки'
        self.fields['address'].help_text = 'Указывайте полный адрес - это важно!'
        self.fields['comments'].label = 'Комментарии к заказу'
        self.fields['date'].label = 'Дата доставки'
        self.fields['date'].help_text = 'Детали доставки уточнит наш менеджер'

astraBaby/astraKroha/views.py
from django.core.mail import EmailMessage
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from decimal import Decimal

from astraBaby.settings import EMAIL_HOST_USER
from .forms import OrderForm
from .models import Category, Product, CartItem, Cart, Order


def index(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    #cart = Cart.objects.first()
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products,
        'cart': cart,
    }
    return render(request, "astraKroha/index.html", context)


def product_view(request, product_slug):
    #cart = Cart.objects.first()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    try:
        product = Product.objects.get(slug=product_slug)
    except:
        product = None
    categories = Category.objects.all()
    context = {
        'product': product,
        'categories': categories,
        'cart': cart,
    }
    return render(request, 'astraKroha/product.html', context)


def category_view(request, category_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    #cart = Cart.objects.first()
    category = Category.objects.get(slug=category_slug)
    categories = Category.objects.all()
    products_of_category = Product.objects.filter(category=category)
    context = {
        'category': category,
        'categories': categories,
        'products_of_category': products_of_category,
        'cart': cart,
    }
    return render(request, 'astraKroha/category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    #cart = Cart.objects.first()
    context = {
        'categories': categories,
        'cart': cart,
    }
    return render(request, 'astraKroha/cart.html', context)


def add_to_cart_view(request):#, product_slug
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    #new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
    #if new_item not in cart.item.all():
    #    cart.item.add(new_item)
    #    cart.save()
    #    return redirect('/cart/')
    cart.add_to_cart(product_slug)
    new_cart_total = 0.00
    for item in cart.item.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.item.count(), 'cart_total_price': cart.cart_total,})#redirect('/cart/')


def remove_from_cart_view(request):#, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    #for cart_item in cart.item.all():
    #    if cart_item.product == product:
    #        cart.item.remove(cart_item)
    #        cart.save()
    #        return redirect('/cart/')
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.item.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.item.count(), 'cart_total_price': cart.cart_total})#return redirect('/cart/')


def update_qty(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    qty = request.GET.get('qty')
    item_id = request.GET.get('item_id')
    cart.change_qty(qty, item_id)
    cart_item = CartItem.objects.get(id=int(item_id))
    return JsonResponse({
        'cart_total': cart.item.count(),
        'item_total': cart_item.item_total,
        'cart_total_price': cart.cart_total
    })


def checkout_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart': cart,
        'categories': categories,
    }
    temp = "позиции и количество: "
    for item in cart.item.all():
        temp += item.product.title + " - " + str(item.qty) + "шт. "
    email_body = "заказ№" + str(cart.id) + " на сумму: " + str(cart.cart_total) + "руб. Детали: " + temp
    email = EmailMessage('Subject', email_body, EMAIL_HOST_USER, to=['sash2005-2@yandex.ru'])
   # email.send()
    return render(request, 'astraKroha/checkout.html', context)


def order_create_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    categories = Category.objects.all()
    context = {
        'form': form,
        'cart': cart,
        'categories': categories,
    }
    return render(request, 'astraKroha/order.html', context)



def make_order_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.item.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order()
        new_order.user=request.user
        new_order.save()
        new_order.items.add(cart)
        new_order.first_name=name
        new_order.last_name=last_name
        new_order.phone=phone
        new_order.address=address
        new_order.buying_type=buying_type
        new_order.comments=comments
        new_order.total = cart.cart_total
        new_order.save()
        del request.session['cart_id']
        del request.session['total']
        return redirect(reverse('thank_you'))


def about_view(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'astraKroha/about.html', context)


def contact_view(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'astraKroha/contact.html', context)


def pay_view(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'astraKroha/pay.html', context)


def delivery_view(request):
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    return render(request, 'astraKroha/delivery.html', context)

astraBaby/astraKroha/templates/astraKroha/about.html
{% extends 'base.html' %}

{% block wrapper %}
<div>
    <h1>
        Магазин товаров для детей «Крошка-Астра» рад приветствовать Вас на своем сайте!
    </h1>
    <p>
        Ассортимент нашего интернет-магазина товаров для детей постоянно пополняется!
        Здесь Вы найдете все, что нужно для счастливого детства: трусики, многоразовые подгузники, товары для гигиены, большой ассортимент одежды,
        игрушек и многое другое для детей от 0. Специально для своих клиентов мы
        отобрали наиболее качественные товары от лучших производителей, поэтому все изделия
        нашего магазина не только функциональные, но и безопасные.
        Все товары имеют сертификаты качества и соответствия.
        Опытные продавцы-консультанты, подробно расскажут Вам об ассортименте, ответят на Ваши
        вопросы и помогут подобрать первый гардероб для Вашего малыша. Мы очень любим своих покупателей.
        Именно поэтому для наших покупателей мы регулярно проводим акции, а для наших постоянных
        покупателей существует накопительная система скидок.
        Магазин детских товаров «Крошка-Астра» – это индивидуальные схемы работы, широкий ассортимент
        и радость на лицах наших покупателей и их детей.
    </p>
</div>
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/cart.html
{% extends 'base.html' %}
{% load static %}
{% block wrapper %}
<div class="page-header">
    <h1>Корзина</h1>
</div>
{% if cart.item.count > 0 %}
<div class="my-cart">
<table>
    <tr>
        <th>Наименование</th>
        <th>Количество</th>
        <th>Цена</th>
    </tr>
    {% for item in cart.item.all %}
    <tr class="cart-item-{{ item.product.id }}">
        <td>{{item.product.title}}</td>
        <td>
            <form action="" method="GET">
                <input type="number" name="qty" class="cart-item-qty" data-id="{{ item.id }}" value="{{ item.qty }}" min="1" style="width:50px" />
            </form>
        </td>
        <td id="cart-item-total-{{ item.id }}">{{ item.item_total }} руб.</td>
        <td><a href="#" class="remove_from_cart button25" data-slug="{{item.product.slug}}" data-id="{{ item.product.id }}">Удалить</a></td>
    </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td><strong>Итого:</strong></td>
        <td id="cart-total-price"><strong>{{ cart.cart_total }} руб.</strong></td>
        <td></td>
    </tr>
</table>
    <br/>
    <hr/>
    <a class="button25" href="{% url 'checkout_view_url' %}">Посмотреть заказ</a>
</div>
<h3 class="cart-empty"></h3>
{% else %}
<div class="page-header">
    <h3>Ваша корзина пуста</h3>
</div>
{% endif %}
<script src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
<script>
    $(document).ready(function(){
        $('.my-empty').css('display', 'none')
        $('.remove_from_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            item_product_id = $(this).attr('data-id')
            console.log(item_product_id)
             data ={
                product_slug: product_slug
            }
            $.ajax({
                type:"GET",
                url:'{% url "remove_from_cart_url" %}',
                data: data,
                success: function(data){
                $("#cart_count").html(data.cart_total)
                $('.cart-item-'+item_product_id).css('display', 'none')
                $('#cart-total-price').html('<strong>'+parseFloat(data.cart_total_price).toFixed(2) + ' руб.</strong>')
                if(parseInt(data.cart_total)==0){
                    $('.my-cart').css('display', 'none')
                    $('.my-empty').css('display', 'block')
                    $('.cart-empty').html('<h3>Ваша корзина пуста</h3>')
                }
            }
            })
        })
    })
    $(document).ready(function(){
        $('.cart-item-qty').on('click', function(){
        qty = $(this).val()
        item_id = $(this).attr('data-id')
        data = {
            qty: qty,
            item_id: item_id
        }
        $.ajax({
            type: "GET",
            url:'{% url "update_qty_url" %}',
            data: data,
            success: function(data){
                 $('#cart-item-total-'+item_id).html(parseFloat(data.item_total).toFixed(2) + ' руб.')
                 console.log(data.cart_total_price)
                 $('#cart-total-price').html('<strong>'+parseFloat(data.cart_total_price).toFixed(2) + ' руб.</strong>')
            }
            })
        })
    })
</script>
{% endblock  %}

astraBaby/astraKroha/templates/astraKroha/category.html
{% extends 'base.html' %}
{% load static %}
{% block wrapper %}
<div class="breadcrumbs">
<a href="{% url 'index_url' %}">Главная</a><span> /</span>
<a href="{{ category.get_absolute_url }}">{{category.name}}</a>
</div>
<div class="page-header">
    <h1>{{category.name}}</h1>
</div>
{% for prod_cat in products_of_category %}
<div class="card-item">
    <a href="{{ prod_cat.get_absolute_url }}"><img src="{{ prod_cat.image.url }}"  /></a>
<a class="card-link" href="{{ prod.get_absolute_url }}"><h5>{{ prod_cat.title }}</h5></a>
    <p class="card-link-p">{{ prod_cat.price }} руб.</p>
    <div class="my-btn">
    <a href="{{ prod_cat.get_absolute_url }}" class="add_to_cart button25" data-slug="{{prod_cat.slug}}">Посмотреть</a>
    </div>
</div>
{% endfor %}
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/checkout.html
{% extends 'base.html' %}

{% block wrapper %}

<div class="page-header">
    <h1>Ваш предварительный заказ</h1>
</div>
<br/>
<div>
<table>
    <tr>
        <th>Наименование</th>
        <th>Количество</th>
        <th>Цена</th>
    </tr>
    {% for item in cart.item.all %}
    <tr>
        <td>{{item.product.title}}</td>
        <td>{{item.qty}}</td>
        <td>{{ item.item_total }} руб.</td>
        <td></tr>
    {% endfor %}
    <tr>
        <td></td>
        <td><strong>Итого:</strong></td>
        <td><strong>{{ cart.cart_total }} руб.</strong></td>
        <td></td>
    </tr>
</table>
</div>
<br/>
<hr/>
<a href="{% url 'order_create_view_url' %}" class="remove_from_cart button25">Оформить заказ</a>
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/contact.html
{% extends 'base.html' %}

{% block wrapper %}
<div class="page-header"><h1>Контакты</h1>
    <h3>телефон: +79623158564</h3>
    <h3>Email: sash20052@gmail.com</h3>
    <h3>Адрес: г. Иркутск, ул. Клары Цеткин, д. 9</h3>
    <h8>Данный сервис проходит отладку и тестирование, приносим извинения за неудобства</h8>
</div>
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/delivery.html
{% extends 'base.html' %}

{% block wrapper %}
<div class="page-header"><h1>Доставка</h1>
    <h3>При наличии товара в офисе вы можете забрать его самостоятильно либо оформить доставку.</h3>
    <h3>Условия доставки</h3>
    <h4>1. Бесплатная доставка по г. Иркутску при стоимости покупки от 3000 рублей.</h4>
    <h4>2. Если стоимость покупки составляет меньше 3000 рублей, то стоимость доставки по г.Иркутску составит 300 рублей.</h4>
    <h4>3. Возможна отправка в регионы, стоимость отправки обсуждается индивидуально.</h4>
</div>
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/index.html
{% extends 'base.html' %}
{% load static %}

{% block wrapper %}




{% block cart_wrapper %}
{% endblock  %}

{% block prod_wrapper %}
{% endblock %}

{% block checkout %}
{% endblock %}

{% include 'astraKroha/tags/product_list.html' %}

{% endblock %}

astraBaby/astraKroha/templates/astraKroha/order.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{{ form.name|crispy }}
{% block wrapper %}
<div class="form-container">
    <form action='{% url "make_order_url" %}' method="POST"> {% csrf_token %}
        <div>{{ form.name|as_crispy_field }}</div>
        <div>{{ form.last_name|as_crispy_field }}</div>
        <div>{{ form.phone|as_crispy_field }}</div>
        <div>{{ form.buying_type|as_crispy_field }}</div>
        <div>{{ form.date|as_crispy_field }}</div>
        <div>{{ form.address|as_crispy_field }}</div>
        <div>{{ form.comments|as_crispy_field }}</div>
        <input type="submit" class="order-button" value="Заказать"/>
    </form>
</div>
<script src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
<script>
        $(document).ready(function(){
            $('#div_id_address').css('display','none')
            $('#id_buying_type').on('click', function(){
                buying_type = $(this).val()
                if(buying_type == 'delivery'){
                    $('#div_id_address').css('display','block')
                }else{
                    $('#div_id_address').css('display','none')
                }
            })
        })
</script>
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/pay.html
{% extends 'base.html' %}

{% block wrapper %}
<div class="page-header"><h1>Оплата</h1>
    <h3>Оплату можно произвести при получении курьеру, в офисе, либо через мобильный банк</h3>
    <h8>Данный сервис проходит отладку и тестирование, приносим извинения за неудобства</h8>
</div>
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/product.html
{% extends 'base.html' %}
{% load static %}
{% block wrapper %}

<div class="breadcrumbs">
<a href="{% url 'index_url' %}">Главная</a><span> /</span>
<a href="{{ product.category.get_absolute_url }}">{{product.category}}</a><span> /</span>
<a href="{{ product.get_absolute_url }}">{{product.title}}</a>
</div>
<div class="product-card">
    <div>
        <img src="{{ product.image.url }}"/>
    </div>
    <div>
        <ul>
            <li><h2>{{product.title}}</h2></li>
            <li><hr/></li>
            <li><br/><p>{{product.description}}</p></li>
            <li><hr/></li>
            <li><br/><h1>{{product.price}} руб.</h1></li>
        </ul>
    </div>
</div>
<br/>
<hr/>
<div class="my-btn">
    <a href="#" class="add_to_cart button25 " data-slug="{{product.slug}}">В корзину</a>
    </div>
<script src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
<script>
    $(document).ready(function(){
        $('.add_to_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            data ={
                product_slug: product_slug
            }
            $.ajax({
                type:"GET",
                url:'{% url "add_to_cart_view_url" %}',
                data: data,
                success: function(data){
                $("#cart_count").html(data.cart_total)

            }
            })
            alert("Товар добавлен в корзину")
        })
    })
</script>
{% endblock %}

astraBaby/astraKroha/templates/astraKroha/thank_you.html
{% extends 'base.html' %}


{% block wrapper %}

<div class='col-sm-8 col-sm-offset-2'>
	<h3 class='text-center'>Спасибо за Ваш заказ! Он принят в обработку. В ближайшее время менеджер с Вами свяжется</h3>
	<p class='text-center'><a href='/'><button class='btn btn-default'>Вернуться в покупкам</button></a></p>
</div>

{% endblock %}